name: voip_calling
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  auto_route: ^7.8.4
  auto_route_generator: ^7.3.2
  bloc: ^8.1.2
  firebase_core: ^2.20.0
  firebase_crashlytics: ^3.4.2
  firebase_messaging: ^14.7.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_callkit_incoming: ^2.0.0+2
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  uuid: ^4.1.0

dev_dependencies:
  bloc_test: ^9.1.2
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.1
  very_good_analysis: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
